Repository CompaniTech/compani-formation, pull requests merged in 2020-11, with the labels that each got.

#141 Com 1599 shadow
  src/components/CalendarIcon/index.tsx
  src/components/CalendarIcon/styles.ts
Labels: dev

#142 Com 1615 refresh
  src/api/programs.ts
  src/screens/explore/About/index.tsx
  src/screens/explore/Catalog/index.tsx
Labels: dev

#143 COM-1602: fix image size for text media & title text media
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TextMediaCard/styles.ts
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/styles.ts
  src/styles/cards.ts
  src/styles/metrics.ts
Labels: dev

#147 Com 1598 quickfix
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseList/styles.ts
  src/screens/explore/Catalog/index.tsx
  src/screens/explore/Catalog/styles.ts
  src/styles/colors.ts
  src/styles/common.ts
Labels: dev

#148 Dev
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseList/styles.ts
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TextMediaCard/styles.ts
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/styles.ts
  src/screens/explore/Catalog/index.tsx
  src/screens/explore/Catalog/styles.ts
  src/styles/cards.ts
  src/styles/colors.ts
  src/styles/common.ts
  src/styles/metrics.ts
Labels: master

#145 COM-1601: ajout d'une barre de progression pour les formations
  src/components/cards/CardHeader/index.tsx
  src/components/cards/ProgressBar/index.tsx
  src/screens/courses/CardContainer/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/CourseProfile/styles.ts
  src/screens/courses/cardTemplates/EndCard/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
  src/store/activities/selectors.ts
  src/store/courses/actions.ts
  src/store/courses/reducers.ts
  src/store/courses/selectors.ts
Labels: dev

#149 COM-1599 counting dates except for progress for calendaricon
  app.json
  src/components/CalendarIcon/index.tsx
Labels: dev

#150 COM-1615 use isCourse in about
  src/screens/explore/About/index.tsx
Labels: dev

#151 Dev
  app.json
  src/components/CalendarIcon/index.tsx
  src/components/cards/CardHeader/index.tsx
  src/components/cards/ProgressBar/index.tsx
  src/screens/courses/CardContainer/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/CourseProfile/styles.ts
  src/screens/courses/cardTemplates/EndCard/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
  src/screens/explore/About/index.tsx
  src/store/activities/selectors.ts
  src/store/courses/actions.ts
  src/store/courses/reducers.ts
  src/store/courses/selectors.ts
Labels: master

#152 COM-1601-refacto: externalize progress calculate
  src/components/CalendarIcon/index.tsx
  src/components/ProgressPieChart/index.tsx
  src/components/steps/OnSiteCell/index.tsx
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/types/StepType.tsx
Labels: dev

#153 COM-1600: see progress for each course on course screen)
  src/components/ProgramCell/index.tsx
  src/components/ProgramCell/styles.ts
  src/components/steps/NextStepCell/index.tsx
  src/screens/courses/CourseList/index.tsx
Labels: dev

#155 COM-1615-navigation: focus on catalog when leave explore and come back
  src/screens/explore/About/index.tsx
Labels: dev

#154 COM-1599-fix-date-when-1-day: fix
  src/components/CalendarIcon/index.tsx
Labels: dev

#157 COM-1637: design profile
  assets/images/aux-joie.png
  assets/images/default_avatar.png
  assets/images/log_out_background.png
  assets/images/profile_background.png
  src/AppContainer/index.tsx
  src/core/helpers/utils.ts
  src/screens/Profile.tsx
  src/screens/Profile/index.tsx
  src/screens/Profile/styles.ts
  src/styles/fonts.js
  src/styles/metrics.ts
  src/types/UserType.ts
Labels: dev

#160 COM-1634 add misc next to programName
  src/components/ProgramCell/index.tsx
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/types/CourseType.tsx
Labels: dev

#162 COM-1632: design for questionnaire type activity
  assets/icons/QuestionnaireIcon.tsx
  src/components/activities/ActivityIcon/index.tsx
  src/types/ActivityType.ts
Labels: dev

#161 COM-1638: update profile infos
  src/AppContainer/index.tsx
  src/api/users.ts
  src/components/ExitModal/index.tsx
  src/components/ExitModal/styles.ts
  src/components/form/Input/index.tsx
  src/components/form/Input/styles.ts
  src/core/data/constants.ts
  src/core/helpers/utils.ts
  src/screens/Authentication/index.tsx
  src/screens/Authentication/styles.ts
  src/screens/ForgotPassword/index.tsx
  src/screens/ForgotPassword/styles.ts
  src/screens/courses/CardContainer/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/Profile/styles.ts
  src/screens/profile/ProfileEdition/index.tsx
  src/screens/profile/ProfileEdition/styles.ts
  src/styles/fonts.js
  src/styles/metrics.ts
Labels: dev

#165 COM-1637-quickfix
  src/screens/profile/Profile/index.tsx
Labels: dev

#164 COM-1615: catalog is the default page for explore wherever we come from
  src/AppContainer/index.tsx
  src/screens/explore/About/index.tsx
Labels: dev

#163 COM-1649: fix overflow
  src/components/cards/FillTheGapProposition/styles.ts
  src/components/cards/FillTheGapQuestion/index.tsx
  src/styles/metrics.ts
Labels: bug

#159 Com 1635
  app.json
  package-lock.json
  package.json
  src/components/cards/Video/index.tsx
  src/components/cards/Video/styles.tsx
  src/core/data/constants.ts
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TextMediaCard/styles.ts
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/styles/colors.ts
  src/styles/metrics.ts
  src/types/CardType.tsx
Labels: dev

#170 COM-1669 - update role in redux
  src/AppContainer/index.tsx
  src/screens/courses/CourseList/index.tsx
  src/store/main/actions.ts
  src/store/main/reducers.ts
  src/store/main/selectors.ts
  src/types/store/MainStoreType.ts
Labels: bug, dev

#169 COM-1635 video on title text media
  src/components/cards/Video/index.tsx
  src/components/cards/Video/styles.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/styles.ts
  src/types/CardType.tsx
Labels: dev

#167 COM-1638-quickfix: margin
  src/components/form/Input/styles.ts
  src/screens/profile/ProfileEdition/index.tsx
  src/screens/profile/ProfileEdition/styles.ts
Labels: dev

#166 COM-1642: update password
  src/AppContainer/index.tsx
  src/api/users.ts
  src/screens/profile/PasswordEdition/index.tsx
  src/screens/profile/PasswordEdition/styles.ts
  src/screens/profile/Profile/index.tsx
  src/screens/profile/Profile/styles.ts
Labels: dev

#172 COM-1637 change image
  assets/images/aux-joie.png
Labels: dev

#171 Com 1636
  src/components/cards/Audio/index.tsx
  src/core/data/constants.ts
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
Labels: dev

#173 Com 1615 navigation3
  src/screens/explore/About/index.tsx
Labels: dev

#175 COM-1637 change image
  assets/images/aux-joie.png
Labels: dev

#174 COM-1632 fix questionnaire icon size
  assets/icons/QuestionnaireIcon.tsx
Labels: dev

#176 Com 1636 design
  src/components/IconButton.tsx
  src/components/cards/Audio/index.tsx
  src/components/cards/Audio/styles.ts
  src/core/data/constants.ts
Labels: dev

#177 COM-1638-feedback : apply Romain's feedbacks
  src/AppContainer/index.tsx
  src/components/form/Input/styles.ts
  src/core/data/constants.ts
  src/screens/profile/ProfileEdition/index.tsx
  src/store/main/reducers.ts
Labels: dev

#179 COM-1647 - update course in courseSlot
  src/types/CourseSlotType.tsx
Labels: dev

#180 Com 1636 progress
  package-lock.json
  package.json
  src/components/cards/Audio/index.tsx
  src/components/cards/Audio/styles.ts
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
Labels: dev

#181 COM-1615 change stack and tab navigator
  src/AppContainer/index.tsx
  src/navigationRef.ts
  src/screens/Authentication/index.tsx
  src/screens/courses/CardContainer/index.tsx
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/cardTemplates/EndCard/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
  src/screens/explore/About/index.tsx
  src/screens/explore/Catalog/index.tsx
  src/screens/profile/Profile/index.tsx
  src/types/NavigationType.tsx
Labels: dev

#182 COM-1673: npm update
  package-lock.json
  package.json
Labels: dependencies

#189 COM-1673: update small packages and apply necessary changes
  .eslintrc.js
  package-lock.json
  package.json
  src/components/cards/ProgressBar/index.tsx
  src/screens/courses/CardContainer/index.tsx
  src/screens/courses/cardTemplates/FlashCard/index.tsx
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
Labels: dependencies

#187 Com 1653 : PR 1
  src/AppContainer/index.tsx
  src/api/users.ts
  src/components/BottomPopUp/index.tsx
  src/components/BottomPopUp/styles.tsx
  src/core/data/constants.ts
  src/screens/Authentication/index.tsx
  src/screens/Authentication/styles.ts
  src/screens/FirstConnection/index.tsx
  src/screens/FirstConnection/styles.ts
Labels: dev

#190 COM-1687 fix <trou> displaying instead of gap
  src/components/cards/FillTheGapQuestion/index.tsx
Labels: dev

#188 COM-1665: add achieved courses section
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseList/styles.ts
  src/screens/courses/CourseProfile/index.tsx
  src/types/CourseType.tsx
Labels: dev

#191 COM-1652 remove useless route + setIsLoading false in profileEdition …
  src/api/programs.ts
  src/screens/profile/PasswordEdition/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
Labels: dev

#193 COM-1666: make app beautiful again
  .expo-shared/assets.json
  assets/images/achieved_background.png
  assets/images/catalog_background.png
  assets/images/elearning_draft_background.png
  assets/images/ongoing_background.png
  assets/images/pa-aidant-balade.png
  src/components/CoursesSection/index.tsx
  src/components/CoursesSection/styles.ts
  src/components/ProgramCell/styles.ts
  src/components/steps/NextStepCell/styles.ts
  src/core/helpers/utils.ts
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseList/styles.ts
  src/screens/explore/Catalog/index.tsx
  src/screens/explore/Catalog/styles.ts
  src/styles/common.ts
Labels: dev
