Repository CompaniTech/compani-formation, pull requests merged in 2020-12, with the labels that each got.

#192 COM-1653: create account
  src/AppContainer/index.tsx
  src/components/CreateAccountForm/index.tsx
  src/components/CreateAccountForm/styles.ts
  src/components/form/Input/index.tsx
  src/components/form/Input/styles.ts
  src/screens/CreateAccount/index.tsx
  src/screens/CreateAccount/styles.ts
  src/screens/FirstConnection/index.tsx
Labels: dev

#195 COM_1664 add description in ProgramCell + mini fix in margin
  src/components/CoursesSection/index.tsx
  src/components/CoursesSection/styles.ts
  src/components/ProgramCell/index.tsx
  src/components/ProgramCell/styles.ts
  src/styles/metrics.ts
Labels: dev

#196 Com 1653 3
  src/api/users.ts
  src/components/CreateAccountForm/index.tsx
  src/context/AuthContext.ts
  src/screens/CreateAccount/index.tsx
Labels: dev

#198 Com 1674
  src/api/activities.ts
  src/api/programs.ts
  src/components/ELearningCell/index.tsx
  src/components/activities/ActivityCell/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
  src/screens/explore/About/index.tsx
  src/screens/explore/Catalog/index.tsx
  src/store/activities/actions.ts
  src/store/activities/reducers.ts
  src/types/store/ActivityStoreType.ts
Labels: dev

#200 COM-1714: update packages
  package-lock.json
  package.json
Labels: dependencies

#201 Com 1711
  src/context/AuthContext.ts
  src/core/data/constants.ts
  src/core/helpers/alenvi.ts
  src/screens/ForgotPassword/index.tsx
Labels: dev

#202 Com 1695: PR1
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/components/ExitModal/index.tsx
  src/components/ExitModal/styles.ts
  src/components/Modal/index.tsx
  src/components/camera/Camera/index.tsx
  src/components/camera/Camera/styles.ts
  src/components/camera/CameraPreview/index.tsx
  src/components/camera/CameraPreview/style.ts
  src/screens/Camera/index.tsx
  src/screens/Camera/styles.ts
  src/screens/profile/Profile/index.tsx
  src/screens/profile/Profile/styles.ts
  src/styles/metrics.ts
Labels: dev

#206 Com 1728
  src/components/ExitModal/styles.ts
  src/components/IconButton.tsx
  src/components/IconButton/index.tsx
  src/components/IconButton/styles.ts
  src/components/cards/QuizProposition/styles.ts
  src/components/form/Input/styles.ts
  src/screens/Authentication/index.tsx
  src/screens/Authentication/styles.ts
  src/screens/explore/About/index.tsx
  src/screens/profile/PasswordEdition/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
  src/styles/metrics.ts
Labels: dev

#207 COM-1704 change deprecated asyncstorage
  package-lock.json
  package.json
  src/core/helpers/asyncStorage.ts
  src/screens/courses/cardTemplates/EndCard/index.tsx
Labels: dev

#205 COM-1653: fix validation button
  src/components/CreateAccountForm/index.tsx
  src/components/CreateAccountForm/styles.ts
  src/components/cards/AnswerTextArea/index.tsx
  src/components/form/Input/index.tsx
  src/screens/CreateAccount/index.tsx
  src/screens/CreateAccount/styles.ts
  src/screens/FirstConnection/index.tsx
  src/screens/FirstConnection/styles.ts
  src/screens/profile/PasswordEdition/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
Labels: dev

#209 COM-1678: go to course when click on nextstepcell
  src/components/steps/NextStepCell/index.tsx
  src/screens/courses/CourseList/index.tsx
Labels: dev

#208 COM-1679: add a title to explanation on quizz cards
  src/components/cards/QuizCardFooter/index.tsx
  src/components/cards/QuizCardFooter/styles.ts
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
  src/screens/courses/cardTemplates/FillTheGapCard/styles.ts
  src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/styles.ts
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/styles.ts
  src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/SingleChoiceQuestionCard/styles.ts
  src/styles/cards.ts
  src/types/CardType.tsx
Labels: dev

#210 COM-1680: add button in courseprofile to go to catalog
  .expo-shared/assets.json
  assets/images/aux-detective.png
  src/components/CoursesSection/index.tsx
  src/components/CoursesSection/styles.ts
  src/screens/courses/CourseList/index.tsx
Labels: dev

#212 Com 1695 2
  .eslintrc.js
  package.json
  src/api/users.ts
  src/components/PictureModal/index.tsx
  src/components/PictureModal/styles.ts
  src/components/camera/Camera/index.tsx
  src/components/camera/CameraPreview/index.tsx
  src/screens/Camera/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/Profile/styles.ts
  src/screens/profile/ProfileEdition/index.tsx
  src/screens/profile/ProfileEdition/styles.ts
  src/types/FormData.ts
Labels: dev

#218 Refacto fill the gap
  src/components/cards/FillTheGapProposition/styles.ts
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
  src/types/CardType.tsx
Labels: dev

#217 COM-1696: group elearning programs by categories
  .expo-shared/assets.json
  assets/images/catalog_background.png
  assets/images/green_section_background.png
  assets/images/ongoing_background.png
  assets/images/pink_section_background.png
  assets/images/purple_section_background.png
  assets/images/yellow_section_background.png
  src/components/CoursesSection/index.tsx
  src/core/helpers/utils.ts
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseList/styles.ts
  src/screens/explore/Catalog/index.tsx
  src/screens/explore/Catalog/styles.ts
Labels: dev

#220 COM-1653: desactiver modification quand retour du back en attente
  src/components/CreateAccountForm/index.tsx
  src/components/form/Input/index.tsx
  src/screens/CreateAccount/index.tsx
  src/screens/EmailForm/index.tsx
Labels: dev

#222 Add icon and splash screen
  .expo-shared/assets.json
  app.json
  assets/images/android_icon.png
  assets/images/compani_logo.png
  assets/images/icon.png
  assets/images/ios_icon.png
  assets/images/splash.png
  src/screens/profile/Profile/index.tsx
Labels: dev

#228 Build ios 1222
  app.json
Labels: master

#229 COM-1735: npm update
  package-lock.json
  package.json
Labels: dependencies

#230 COM-1676: refacto progress pie chart
  src/components/CalendarIcon/index.tsx
  src/components/ELearningCell/index.tsx
  src/components/ProgramCell/index.tsx
  src/components/ProgressPieChart/index.tsx
Labels: dev

#231 COM-1724: updated axios
  package-lock.json
  package.json
Labels: dependencies

#215 Com 1695 3
  app.json
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/components/PictureModal/index.tsx
  src/components/camera/Camera/index.tsx
  src/components/camera/CameraPreview/index.tsx
  src/core/data/constants.ts
  src/core/helpers/pictures.ts
  src/screens/Camera/index.tsx
  src/screens/ImagePickerManager/index.tsx
  src/screens/ImagePickerManager/styles.ts
  src/types/NavigationType.tsx
Labels: dev

#232 Com 1779
  package-lock.json
  src/screens/Authentication/index.tsx
Labels: bug

#233 COM-1713
  src/api/authentication.ts
  src/context/AuthContext.ts
  src/screens/CreateAccount/index.tsx
Labels: dev

#234 Update build number
  app.json
Labels: dev
