Repository CompaniTech/compani-formation, pull requests merged in 2021-09, with the labels that each got.

#391 COM-2291: npm update
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/components/ForgotPasswordModal/index.tsx
  src/components/PasswordForm/index.tsx
  src/context/AuthContext.ts
  src/core/helpers/alenvi.ts
  src/screens/CreateAccount/index.tsx
  src/screens/courses/ActivityCardContainer/index.tsx
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/QuestionnaireCardContainer/index.tsx
  src/screens/courses/SubProgramProfile/index.tsx
  src/screens/explore/Catalog/index.tsx
  src/screens/explore/ELearningAbout/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
Labels: dependencies

#392 Com 2316
  .github/workflows/integration-tests.yml
  App/index.tsx
  __tests__/authentication.test.js
  environment.js
  environment.ts
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/api/activities.ts
  src/api/activityHistories.ts
  src/api/authentication.ts
  src/api/courses.ts
  src/api/programs.ts
  src/api/questionnaireHistories.ts
  src/api/questionnaires.ts
  src/api/subPrograms.ts
  src/api/users.ts
  src/api/version.ts
  src/components/CoursesSection/index.tsx
  src/context/AuthContext.ts
  src/core/helpers/asyncStorage.ts
  src/types/QuestionnaireType.ts
Labels: dev

#396 Com 2306
  src/api/companies.ts
  src/api/companyLinkRequests.ts
  src/components/BottomModal/index.tsx
  src/components/BottomModal/styles.ts
  src/components/ForgotPasswordModal/index.tsx
  src/components/ForgotPasswordModal/styles.ts
  src/components/InternalRulesModal/index.tsx
  src/components/TermOfUseModal/index.tsx
  src/components/companyLinkRequest/CompanySearchModal/index.tsx
  src/components/companyLinkRequest/CompanySearchModal/styles.ts
  src/components/companyLinkRequest/ValidationModal/index.tsx
  src/components/companyLinkRequest/ValidationModal/styles.ts
  src/screens/EmailForm/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/Profile/styles.ts
  src/store/main/reducers.ts
  src/styles/rulesModal.ts
  src/types/CompanyType.ts
  src/types/UserType.ts
Labels: dev

#397 COM-2306: fix bold company name
  src/screens/profile/Profile/index.tsx
  src/screens/profile/Profile/styles.ts
Labels: dev

#398 MAJ version for mep
  app.json
Labels: dev

#400 COM-2349: npm update
  package-lock.json
  package.json
Labels: dependencies

#402 COM-2336: remove validation button on single choice question
  src/components/cards/QuizCardFooter/index.tsx
  src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx
Labels: dev

#405 Com 2339
  src/components/cards/FillTheGapQuestion/index.tsx
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
Labels: dev

#404 COM-2338: improve cells section UI
  src/components/CoursesSection/index.tsx
  src/components/CoursesSection/styles.ts
  src/components/steps/NextStepCell/styles.ts
  src/styles/metrics.ts
Labels: dev

#403 Com 2340
  src/components/CourseProfileStickyHeader/index.tsx
  src/components/CourseProfileStickyHeader/styles.ts
  src/components/cards/CardHeader/index.tsx
  src/components/cards/ProgressBar/styles.ts
  src/screens/CreateAccount/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/styles/common.ts
  src/styles/metrics.ts
Labels: dev

#408 MEP 29/09 - build number
  app.json
Labels: dev

#409 MEP 29/09
  app.json
  package-lock.json
  package.json
  src/components/CourseProfileStickyHeader/index.tsx
  src/components/CourseProfileStickyHeader/styles.ts
  src/components/CoursesSection/index.tsx
  src/components/CoursesSection/styles.ts
  src/components/cards/CardFooter/index.tsx
  src/components/cards/CardHeader/index.tsx
  src/components/cards/FillTheGapQuestion/index.tsx
  src/components/cards/ProgressBar/styles.ts
  src/components/cards/QuestionCardFooter/index.tsx
  src/components/cards/QuizCardFooter/index.tsx
  src/components/steps/NextStepCell/styles.ts
  src/screens/CreateAccount/index.tsx
  src/screens/courses/ActivityCardContainer/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/QuestionnaireCardContainer/index.tsx
  src/screens/courses/cardTemplates/ActivityEndCard/index.tsx
  src/screens/courses/cardTemplates/CardTemplate/index.tsx
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
  src/screens/courses/cardTemplates/FlashCard/index.tsx
  src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx
  src/screens/courses/cardTemplates/QuestionnaireEndCard/index.tsx
  src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/screens/courses/cardTemplates/Transition/index.tsx
  src/store/cards/actions.ts
  src/styles/common.ts
  src/styles/metrics.ts
  src/types/store/CardStoreType.ts
Labels: master
