Repository CompaniTech/compani-formation, pull requests merged in 2021-03, with the labels that each got.

#317 COM-1934: npm update
  package-lock.json
  package.json
Labels: dependencies

#318 COM-1896: add optional on field
  src/components/CreateAccountForm/index.tsx
  src/components/form/Input/index.tsx
Labels: dev

#319 Com 1893
  assets/icons/CatalogIcon.tsx
  assets/icons/CatalogSelectedIcon.tsx
  assets/icons/CoursesIcon.tsx
  assets/icons/CoursesSelectedIcon.tsx
  assets/icons/ProfileIcon.tsx
  assets/icons/ProfileSelectedIcon.tsx
  src/AppContainer/index.tsx
  src/AppContainer/styles.ts
  src/styles/metrics.ts
Labels: dev

#320 COM-1838 first draft for firebase
  .gitignore
  App.tsx
  app.json
  package-lock.json
  package.json
Labels: dev

#322 Com 1964
  app.json
  environment.js
Labels: dev

#324 update version for mep
  app.json
Labels: dev

#326 COM-1969: npm update
  package-lock.json
  package.json
Labels: dependencies

#321 COM-1839 log eventwhen changing screen
  src/AppContainer/index.tsx
  src/AppContainer/styles.ts
  src/Home/index.tsx
  src/Home/styles.ts
  src/core/helpers/analytics.ts
Labels: dev

#327 COM-1957 : show draft program section for testers
  src/screens/courses/CourseList/index.tsx
Labels: dev

#330 MEP 26/03
  app.json
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/AppContainer/styles.ts
  src/Home/index.tsx
  src/Home/styles.ts
  src/core/helpers/analytics.ts
  src/screens/courses/CourseList/index.tsx
Labels: master

#331 change ios version
  app.json
Labels: dev

#328 COM-1951: remove questionnaire
  assets/icons/QuestionnaireIcon.tsx
  src/components/activities/ActivityIcon/index.tsx
  src/core/data/constants.ts
  src/types/ActivityType.ts
Labels: dev
