Repository CompaniTech/compani-formation, pull requests merged in 2021-10, with the labels that each got.

#412 update build number
  app.json
Labels: dev

#410 [ne pas fusionner] COM-2344: update node js
  .github/workflows/integration-tests.yml
  .github/workflows/lint.yml
  package-lock.json
Labels: dependencies

#411 COM-2397: npm update
  package-lock.json
  package.json
  src/core/helpers/asyncStorage.ts
  src/core/helpers/dates.ts
Labels: dependencies

#418 MEP 15/10
  .github/workflows/integration-tests.yml
  .github/workflows/lint.yml
  app.json
  package-lock.json
  package.json
  src/components/Spinner/index.tsx
  src/components/Spinner/styles.ts
  src/components/cards/Image/index.tsx
  src/components/cards/Image/styles.ts
  src/components/cards/Video/index.tsx
  src/components/cards/Video/styles.tsx
  src/components/steps/LiveCell/index.tsx
  src/components/steps/LiveCell/styles.ts
  src/components/steps/LiveCellInfoModal/index.tsx
  src/components/steps/LiveCellInfoModal/styles.ts
  src/components/steps/LiveHoursDisplay/index.tsx
  src/components/steps/LiveHoursDisplay/styles.ts
  src/components/steps/LiveInfoItem/index.tsx
  src/components/steps/LiveInfoItem/styles.ts
  src/components/steps/OnSiteInfoItem/index.tsx
  src/core/data/constants.ts
  src/core/helpers/asyncStorage.ts
  src/core/helpers/dates.ts
  src/screens/courses/ActivityCardContainer/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/QuestionnaireCardContainer/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
  src/screens/courses/cardTemplates/StartCard/styles.ts
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TextMediaCard/styles.ts
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/styles.ts
  src/styles/metrics.ts
  src/types/CacheType.ts
  src/types/CourseTypes.tsx
  src/types/StepTypes.tsx
Labels: master
