Repository CompaniTech/compani-formation, pull requests merged in 2021-04, with the labels that each got.

#333 Update rules
  src/core/data/rules.ts
Labels: dev

#334 Update rules
  src/core/data/rules.ts
Labels: master

#335 Change check version
  App.tsx
  src/api/version.ts
  src/core/data/constants.ts
Labels: dev

#336 Com 1984 : npm update
  package-lock.json
  package.json
  src/components/cards/ProgressBar/index.tsx
  src/screens/ImagePickerManager/index.tsx
Labels: dependencies

#339 Com 1995
  App.tsx
  assets/fonts/FiraSans-SemiBoldItalic.ttf
  assets/icons/QuestionnaireIcon.tsx
  src/api/questionnaires.ts
  src/components/CoursesSection/index.tsx
  src/components/questionnaires/QuestionnaireCell/index.tsx
  src/components/questionnaires/QuestionnaireCell/styles.ts
  src/components/questionnaires/QuestionnairesContainer/index.tsx
  src/components/questionnaires/QuestionnairesContainer/styles.ts
  src/core/helpers/utils.ts
  src/screens/courses/CourseProfile/index.tsx
  src/styles/fonts.js
  src/styles/metrics.ts
  src/types/QuestionnaireType.ts
Labels: dev

#341 Upgrade expo
  package-lock.json
  package.json
  src/screens/explore/Catalog/styles.ts
  src/styles/fonts.js
  tsconfig.json
Labels: dependencies, dev

#343 COM-1995 - Fix Romain's review
  src/components/questionnaires/QuestionnairesContainer/index.tsx
  src/components/questionnaires/QuestionnairesContainer/styles.ts
Labels: dev

#342 Com 2021 refacto
  src/api/authentication.ts
  src/components/CreateAccountForm/index.tsx
  src/components/ExitModal/index.tsx
  src/components/PasswordForm/index.tsx
  src/components/form/Input/index.tsx
  src/core/helpers/alenvi.ts
  src/screens/Authentication/index.tsx
  src/screens/EmailForm/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
  src/types/CourseSlotType.ts
  src/types/NavigationType.ts
  src/types/SubProgramType.ts
Labels: dev

#344 COM-2014: can save questionnaire history
  src/api/questionnaireHistories.ts
  src/screens/courses/QuestionnaireCardContainer/index.tsx
  src/screens/courses/cardTemplates/ActivityEndCard/index.tsx
  src/screens/courses/cardTemplates/QuestionnaireEndCard/index.tsx
Labels: dev

#347 change versions
  app.json
Labels: dev

#349 Com 2054
  package-lock.json
  package.json
Labels: dependencies, dev

#350 Com 2018
  package-lock.json
  src/components/About/index.tsx
  src/components/CoursesSection/index.tsx
  src/components/CreateAccountForm/index.tsx
  src/components/ForgotPasswordModal/index.tsx
  src/components/PasswordForm/index.tsx
  src/components/PictureModal/index.tsx
  src/components/UpdateAppModal/index.tsx
  src/components/camera/CameraPreview/index.tsx
  src/components/camera/CameraPreview/style.ts
  src/components/cards/QuestionCardFooter/index.tsx
  src/components/form/Button/index.tsx
  src/components/form/Button/styles.ts
  src/components/form/PrimaryButton/index.tsx
  src/components/form/SecondaryButton/index.tsx
  src/screens/Authentication/index.tsx
  src/screens/EmailForm/index.tsx
  src/screens/courses/cardTemplates/ActivityEndCard/index.tsx
  src/screens/courses/cardTemplates/QuestionnaireEndCard/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
Labels: dev
