Repository CompaniTech/compani-formation, pull requests merged in 2021-02, with the labels that each got.

#279 update checklist
  .github/pull_request_template.md
Labels: dev

#286 Com 1815 2
  src/components/ForgotPasswordModal/index.tsx
  src/screens/EmailForm/index.tsx
Labels: dev

#288 COM-1811: change bg color and add margin
  src/components/InternalRulesModal/index.tsx
  src/components/InternalRulesModal/styles.ts
  src/styles/colors.ts
Labels: dev

#289 COM-1810: add icons for contact
  src/screens/explore/BlendedAbout/index.tsx
  src/screens/explore/BlendedAbout/styles.ts
Labels: dev

#287 COM-1869 - npm update - Fix package-lock
  __tests__/authentication.test.js
  package-lock.json
  package.json
Labels: dev

#290 Com 1863
  src/components/cards/OrderProposition/index.tsx
Labels: dev

#294 COM-1863 - Fix design
  src/components/cards/OrderProposition/index.tsx
  src/components/cards/OrderProposition/styles.ts
Labels: dev

#293 Com 1849
  src/components/cards/SurveyScoreSelector/styles.ts
  src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx
  src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
  src/store/activities/actions.ts
  src/store/activities/reducers.ts
  src/styles/colors.ts
  src/types/CardType.tsx
  src/types/store/ActivityStoreType.ts
Labels: dev

#295 COM-1871 add style for link
  src/styles/common.ts
Labels: dev

#296 COM-1847 can switch answers on fill the gap card
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
  src/types/CardType.tsx
Labels: dev

#292 COM-1858 - Add sentry
  App.tsx
  app.json
  package-lock.json
  package.json
Labels: dev

#297 Com 1792
  src/components/CoursesSection/index.tsx
  src/components/CreateAccountForm/index.tsx
  src/components/ELearningCell/index.tsx
  src/components/PictureModal/index.tsx
  src/components/activities/ActivityCell/index.tsx
  src/components/activities/ActivityList/index.tsx
  src/components/cards/CardFooter/index.tsx
  src/components/cards/QuestionCardFooter/index.tsx
  src/components/steps/NextStepCell/index.tsx
  src/components/steps/OnSiteCell/index.tsx
  src/screens/Camera/index.tsx
  src/screens/CreateAccount/index.tsx
  src/screens/ImagePickerManager/index.tsx
  src/screens/courses/CourseList/index.tsx
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/SubProgramProfile/index.tsx
  src/screens/courses/cardTemplates/EndCard/index.tsx
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
  src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
Labels: dev

#299 COM-1863 - Change dragButton color when validated
  src/components/cards/OrderProposition/index.tsx
Labels: dev

#300 COM-1862 - Change lineHeigth for better UI
  src/styles/cards.ts
  src/styles/metrics.ts
Labels: dev

#301 COM-1837: change fonts
  assets/fonts/FiraSans-Black.ttf
  assets/fonts/FiraSans-Bold.ttf
  assets/fonts/FiraSans-Italic.ttf
  assets/fonts/FiraSans-Medium.ttf
  assets/fonts/FiraSans-Regular.ttf
  assets/fonts/Nunito-Black.ttf
  assets/fonts/Nunito-BoldItalic.ttf
  assets/fonts/Nunito-Light.ttf
  assets/fonts/Nunito-Regular.ttf
  assets/fonts/Nunito-SemiBold.ttf
Labels: dev

#302 COM-1862 - Romain veut tester du 24
  src/styles/metrics.ts
Labels: dev

#303 COM-1721: preload assets images
  App.tsx
  assets/images/aux_detective.png
  assets/images/aux_joie.png
  assets/images/pa_aidant_balade.png
  package-lock.json
  package.json
  src/components/CoursesSection/index.tsx
  src/screens/courses/CourseList/index.tsx
  src/screens/explore/Catalog/index.tsx
  src/screens/profile/Profile/index.tsx
Labels: dev

#298 Com 1790 - Swipe
  src/screens/courses/CardContainer/index.tsx
  src/screens/courses/cardTemplates/CardTemplate.tsx
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
  src/screens/courses/cardTemplates/FlashCard/index.tsx
  src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx
  src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/screens/courses/cardTemplates/Transition/index.tsx
Labels: dev

#307 COM-1790 swipe sensibility
  src/core/data/constants.ts
  src/screens/courses/CardContainer/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
Labels: dev

#309 COM-1913 cant dismiss cardContainer
  src/AppContainer/index.tsx
Labels: dev

#308 Com 1902
  package-lock.json
  package.json
Labels: dependencies

#310 Update checklist in PR template
  .github/pull_request_template.md
Labels: dev

#311 COM-1899: term of use modal
  src/components/CreateAccountForm/index.tsx
  src/components/CreateAccountForm/styles.ts
  src/components/InternalRulesModal/index.tsx
  src/components/TermOfUseModal/index.tsx
  src/core/data/rules.ts
  src/screens/CreateAccount/index.tsx
  src/screens/explore/BlendedAbout/index.tsx
  src/styles/rulesModal.ts
Labels: dev

#312 COM-1899: modal text at page bottom
  src/components/CreateAccountForm/index.tsx
  src/components/CreateAccountForm/styles.ts
  src/core/data/rules.ts
Labels: dev

#314 Com 1899 button
  src/components/CreateAccountForm/index.tsx
  src/components/CreateAccountForm/styles.ts
  src/screens/EmailForm/index.tsx
  src/screens/EmailForm/styles.ts
  src/styles/accountCreation.ts
Labels: bug, dev

#315 change version and build number
  app.json
Labels: dev

#316 MEP 02/03
  .github/pull_request_template.md
  app.json
  package-lock.json
  package.json
  src/AppContainer/index.tsx
  src/components/CreateAccountForm/index.tsx
  src/components/CreateAccountForm/styles.ts
  src/components/InternalRulesModal/index.tsx
  src/components/TermOfUseModal/index.tsx
  src/components/ZoomImage/index.tsx
  src/components/ZoomImage/styles.ts
  src/core/data/constants.ts
  src/core/data/rules.ts
  src/screens/CreateAccount/index.tsx
  src/screens/EmailForm/index.tsx
  src/screens/EmailForm/styles.ts
  src/screens/courses/CardContainer/index.tsx
  src/screens/courses/cardTemplates/CardTemplate.tsx
  src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
  src/screens/courses/cardTemplates/FlashCard/index.tsx
  src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx
  src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
  src/screens/courses/cardTemplates/TextMediaCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextCard/index.tsx
  src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
  src/screens/courses/cardTemplates/Transition/index.tsx
  src/screens/explore/BlendedAbout/index.tsx
  src/styles/accountCreation.ts
  src/styles/rulesModal.ts
Labels: master
