Repository CompaniTech/compani-formation, pull requests merged in 2021-11, with the labels that each got.

#424 COM-2489: npm update
  .github/workflows/integration-tests.yml
  package-lock.json
  package.json
  src/components/cards/Video/index.tsx
  src/screens/courses/ActivityCardContainer/index.tsx
  src/screens/courses/QuestionnaireCardContainer/index.tsx
  src/screens/courses/SubProgramProfile/index.tsx
Labels: dependencies

#426 COM-2538: fix day bug
  src/components/CalendarIcon/index.tsx
  src/core/helpers/dates.ts
  src/screens/explore/BlendedAbout/index.tsx
Labels: bug

#429 COM-2199 add constant in context
  src/context/AuthContext.ts
  src/core/data/constants.ts
Labels: dev
