Repository CompaniTech/compani-formation, pull requests merged in 2022-03, with the labels that each got.

#448 COM-2721: display theoretical duration for steps
  src/components/ELearningCell/index.tsx
  src/components/steps/StepCellTitle/index.tsx
  src/core/helpers/utils.ts
  src/types/StepTypes.tsx
Labels: dev

#450 mep-18-03: build version
  app.json
Labels: dev

#451 MEP-18-03
  app.json
  package-lock.json
  package.json
  src/components/ELearningCell/index.tsx
  src/components/ProgramCell/index.tsx
  src/components/ProgramCell/styles.ts
  src/components/steps/StepCellTitle/index.tsx
  src/core/helpers/utils.ts
  src/screens/courses/CourseList/index.tsx
  src/screens/explore/Catalog/index.tsx
  src/types/StepTypes.tsx
Labels: master

#456 MEP a la volée 28/03
  src/core/helpers/utils.ts
Labels: bug, master

#453 COM-2758: download completion certificate
  package-lock.json
  package.json
  src/api/courses.ts
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/CourseProfile/styles.ts
  src/types/AxiosTypes.ts
Labels: dev

#457 COM-2758: display download button
  src/screens/courses/CourseProfile/index.tsx
  src/types/CourseTypes.tsx
Labels: dev
