Repository CompaniTech/compani-formation, pull requests merged in 2022-08, with the labels that each got.

#481 COM-2929: can scroll big flatlist
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/styles.ts
Labels: bug, dev

#482 Com 2965
  .gitignore
  __tests__/authentication.test.js
  app.config.js
  app.json
  babel.config.js
  eas.json
  environment.ts
  index.js
  package-lock.json
  package.json
  src/App/index.tsx
  src/AppContainer/index.tsx
  src/core/data/constants.ts
  src/core/helpers/notifications.ts
Labels: dev, dependencies

#483 COM-2934 refacto companiDate factory
  src/components/CalendarIcon/index.tsx
  src/components/steps/LiveCell/index.tsx
  src/components/steps/LiveCellInfoModal/index.tsx
  src/components/steps/LiveHoursDisplay/index.tsx
  src/components/steps/LiveInfoItem/index.tsx
  src/core/helpers/asyncStorage.ts
  src/core/helpers/dates.ts
  src/core/helpers/dates/companiDates.ts
  src/core/helpers/dates/luxon.ts
  src/core/helpers/dates/utils.ts
  src/screens/courses/CourseList/index.tsx
  src/screens/explore/BlendedAbout/index.tsx
Labels: dev

#484 Com 2965 expo publish
  app.config.js
  environment.ts
  src/core/data/constants.ts
Labels: dev

#485 COM-2934 update luxon and @type/luxon
  package-lock.json
  package.json
Labels: dev, dependencies

#486 COM-2973: add tablet test on github
  .github/pull_request_template.md
Labels: dev
