Repository CompaniTech/compani-formation, pull requests merged in 2022-09, with the labels that each got.

#487 COM-2988 - update PR template link
  .github/pull_request_template.md
Labels: dev

#488 COM-2931: refacto colors
  src/styles/colors.ts
Labels: dev

#491 Com 2974
  assets/icons/LearnerCoursesIcon.tsx
  assets/icons/LearnerCoursesSelectedIcon.tsx
  assets/icons/TrainerCoursesIcon.tsx
  assets/icons/TrainerCoursesSelectedIcon.tsx
  assets/images/pa_aidant_balade.png
  assets/images/pa_aidant_balade_bleu.png
  assets/images/pa_aidant_balade_rose.png
  src/context/AuthContext.ts
  src/core/data/constants.ts
  src/core/helpers/assets.ts
  src/navigation/Home/index.tsx
  src/navigation/Home/styles.ts
  src/screens/courses/CourseProfile/index.tsx
  src/screens/courses/SubProgramProfile/index.tsx
  src/screens/courses/list/LearnerCourses/index.tsx
  src/screens/courses/list/TrainerCourses/index.tsx
  src/screens/courses/list/styles.ts
  src/types/NavigationType.ts
Labels: dev

#489 Com 2965 app config
  app.config.js
Labels: bug, dev

#492 COM-2984:expo 45
  package-lock.json
  package.json
  src/components/ForgotPasswordModal/index.tsx
  src/components/PasswordForm/index.tsx
  src/components/camera/Camera/index.tsx
  src/components/cards/AnswerTextArea/index.tsx
  src/components/cards/Video/index.tsx
  src/components/form/Input/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
Labels: dependencies

#490 COM-2965 - remove reactotron
  .gitignore
  package-lock.json
  package.json
Labels: dev

#493 COM-2983: can't show activity on non-elearning step
  src/components/steps/LiveCell/index.tsx
  src/screens/courses/CourseProfile/index.tsx
Labels: dev

#495 COM-2986: use percentages
  src/screens/courses/list/styles.ts
  src/screens/explore/Catalog/styles.ts
Labels: dev

#497 COM-2989: able access to trainer course profile
  src/api/courses.ts
  src/components/CalendarIcon/index.tsx
  src/components/CourseProfileHeader/index.tsx
  src/components/CourseProfileHeader/styles.ts
  src/components/activities/ActivityCell/index.tsx
  src/components/form/Button/index.tsx
  src/components/form/Button/styles.ts
  src/components/form/PrimaryButton/index.tsx
  src/components/form/SecondaryButton/index.tsx
  src/components/steps/LiveCell/index.tsx
  src/components/steps/NextStepCell/index.tsx
  src/core/data/constants.ts
  src/navigation/AppNavigation/index.tsx
  src/screens/courses/ActivityCardContainer/index.tsx
  src/screens/courses/CourseProfile/styles.ts
  src/screens/courses/QuestionnaireCardContainer/index.tsx
  src/screens/courses/list/LearnerCourses/index.tsx
  src/screens/courses/list/TrainerCourses/index.tsx
  src/screens/courses/profile/LearnerCourseProfile/index.tsx
  src/screens/courses/profile/TrainerCourseProfile/index.tsx
  src/screens/courses/profile/helper.tsx
  src/screens/courses/profile/styles.ts
  src/screens/explore/BlendedAbout/index.tsx
  src/screens/explore/ELearningAbout/index.tsx
  src/store/courses/actions.ts
  src/store/courses/reducers.ts
  src/types/FontType.ts
  src/types/NavigationType.ts
  src/types/store/CourseStoreType.ts
Labels: dev

#500 COM-3009: refacto camera
  src/components/PictureModal/index.tsx
  src/components/camera/Camera/index.tsx
  src/components/camera/CameraModal/index.tsx
  src/components/camera/CameraModal/styles.ts
  src/components/camera/CameraPreview/index.tsx
  src/core/helpers/pictures.ts
  src/navigation/AppNavigation/index.tsx
  src/screens/Camera/index.tsx
  src/screens/Camera/styles.ts
  src/screens/profile/Profile/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
  src/types/NavigationType.ts
Labels: dev

#501 Com 3011
  .expo-shared/assets.json
  src/components/ImagePickerManager/index.tsx
  src/components/ImagePickerManager/styles.ts
  src/components/PictureModal/index.tsx
  src/navigation/AppNavigation/index.tsx
  src/screens/ImagePickerManager/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
Labels: dev

#504 Com 2977
  src/api/courses.ts
  src/components/About/index.tsx
  src/components/About/styles.ts
  src/components/CourseAboutHeader/index.tsx
  src/components/CourseAboutHeader/styles.ts
  src/components/PersonCell/index.tsx
  src/components/PersonCell/styles.ts
  src/core/helpers/notifications.ts
  src/navigation/AppNavigation/index.tsx
  src/screens/courses/profile/AdminCourseProfile/index.tsx
  src/screens/courses/profile/LearnerCourseProfile/index.tsx
  src/screens/courses/profile/TrainerCourseProfile/index.tsx
  src/screens/courses/profile/styles.ts
  src/types/CourseTypes.tsx
  src/types/FeatherType.ts
  src/types/NavigationType.ts
  src/types/UserType.ts
Labels: dev

#506 COM-2994: replace route
  src/api/courses.ts
  src/screens/courses/list/LearnerCourses/index.tsx
  src/screens/profile/Profile/index.tsx
  src/types/AxiosTypes.ts
Labels: dev

#509 mep-30-09: prepare mep
  app.config.js
  src/navigation/Home/index.tsx
Labels: dev
