Repository CompaniTech/compani-formation, pull requests merged in 2023-09, with the labels that each got.

#562 COM-3535: rename variable
  src/types/CourseTypes.tsx
Labels: bug

#565 MEP mobile 08/09
  .github/workflows/integration-tests.yml
  .github/workflows/ts-lint.yml
  __tests__/authentication.test.js
  app.config.js
  eas.json
  mock.js
  package.json
  src/components/ImagePickerManager/index.tsx
  src/components/camera/CameraModal/index.tsx
  src/core/helpers/notifications.ts
  src/core/helpers/pictures.ts
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/profile/AdminCourseProfile/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
  src/types/CourseTypes.tsx
  src/types/PictureTypes.tsx
  yarn.lock
Labels: master

#564 update-version-2-20-0: update version to 2.20.0
  app.config.js
  eas.json
Labels: dev

#567 update-version-2-19-0-1: update version to 2.19.0.1
  app.config.js
  eas.json
Labels: dev

#569 update-version-2-19-0-1-2 update ios version to 2.19.0.1
  app.config.js
  eas.json
Labels: dev

#568 MEP intermédiaire
  app.config.js
Labels: master

#571 update-version-2-19-0-2: update version to 2.19.0.2
  app.config.js
  eas.json
Labels: dev

#573 update-version-2-19-0-2: update version to 2.19.0.2
  app.config.js
Labels: dev

#572 MEP intermédiaire 12/09
  app.config.js
Labels: master

#566 Remove sharp-cli
  package.json
  yarn.lock
Labels: bug, dev

#574 Com 3522 rebase
  app.config.js
  environment.ts
  src/api/questionnaires.ts
  src/components/QuestionnaireQRCodeCell/index.tsx
  src/components/QuestionnaireQRCodeCell/styles.ts
  src/core/data/constants.ts
  src/screens/courses/profile/AdminCourseProfile/index.tsx
  src/styles/fonts.js
Labels: dev

#576 update-version-2-20-0-3: update version to 2.20.0
  app.config.js
  eas.json
Labels: dev

#578 Com 3544
  src/components/PersonCell/index.tsx
  src/components/PersonCell/styles.ts
  src/types/UserType.ts
Labels: dev

#575 Com 3543
  src/api/authentication.ts
  src/components/FirstConnectionModal/index.tsx
  src/components/FirstConnectionModal/styles.ts
  src/components/ForgotPasswordModal/index.tsx
  src/components/ForgotPasswordModal/styles.ts
  src/components/PasswordForm/index.tsx
  src/components/PasswordForm/styles.ts
  src/components/form/Button/styles.ts
  src/components/form/Input/index.tsx
  src/navigation/AppNavigation/index.tsx
  src/screens/Authentication/index.tsx
  src/screens/EmailForm/index.tsx
  src/screens/LoginCodeForm/index.tsx
  src/screens/LoginCodeForm/styles.ts
  src/screens/PasswordReset/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
  src/styles/fonts.js
  src/types/NavigationType.ts
Labels: dev

#579 MEP 22/09
  app.config.js
  eas.json
  environment.ts
  package.json
  src/api/authentication.ts
  src/api/companies.ts
  src/api/questionnaires.ts
  src/components/CompanySearchModal/index.tsx
  src/components/CompanySearchModal/styles.ts
  src/components/FirstConnectionModal/index.tsx
  src/components/FirstConnectionModal/styles.ts
  src/components/ForgotPasswordModal/index.tsx
  src/components/ForgotPasswordModal/styles.ts
  src/components/PasswordForm/index.tsx
  src/components/PasswordForm/styles.ts
  src/components/PersonCell/index.tsx
  src/components/PersonCell/styles.ts
  src/components/QuestionnaireQRCodeCell/index.tsx
  src/components/QuestionnaireQRCodeCell/styles.ts
  src/components/companyLinkRequest/CompanySearchModal/index.tsx
  src/components/companyLinkRequest/ValidationModal/index.tsx
  src/components/form/Button/styles.ts
  src/components/form/Input/index.tsx
  src/core/data/constants.ts
  src/core/helpers/utils.ts
  src/navigation/AppNavigation/index.tsx
  src/screens/Authentication/index.tsx
  src/screens/EmailForm/index.tsx
  src/screens/LoginCodeForm/index.tsx
  src/screens/LoginCodeForm/styles.ts
  src/screens/PasswordReset/index.tsx
  src/screens/courses/profile/AdminCourseProfile/index.tsx
  src/screens/profile/Profile/index.tsx
  src/screens/profile/ProfileEdition/index.tsx
  src/styles/fonts.js
  src/types/NavigationType.ts
  src/types/UserType.ts
  yarn.lock
Labels: master
