Repository CompaniTech/compani-formation, pull requests merged in 2023-02, with the labels that each got.

#546 fix releaseChannel version
  eas.json
Labels: dev

#547 Mini fix MES-03/02
  eas.json
Labels: master

#548 COM-3338 - remove preinstall commmand
  package.json
Labels: bug, dev
