Repository CompaniTech/compani-formation, pull requests merged in 2024-03, with the labels that each got.

#607 update version to 2.24.0
  app.config.js
  eas.json
Labels: dev

#608 COM-3667: use react-native-gesture-handler API 2 for zoom
  jest.setup.js
  src/components/ZoomImage/index.tsx
  src/screens/courses/profile/AdminCourseProfile/index.tsx
Labels: dev

#609 COM-3668 - change labels in Survey card
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
  src/types/CardType.tsx
Labels: dev

#610 MEP - 19/03/2024
  app.config.js
  eas.json
  jest.setup.js
  src/components/ZoomImage/index.tsx
  src/core/helpers/dates/utils.ts
  src/screens/courses/ActivityCardContainer/index.tsx
  src/screens/courses/cardTemplates/ActivityEndCard/index.tsx
  src/screens/courses/cardTemplates/StartCard/index.tsx
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
  src/screens/courses/profile/AdminCourseProfile/index.tsx
  src/types/CardType.tsx
Labels: master

#611 npm update SDK 50
  app.config.js
  babel.config.js
  mock.js
  package.json
  src/App/index.tsx
  src/components/ProgressPieChart/ProgressCircle.tsx
  src/components/ProgressPieChart/index.tsx
  src/components/ProgressPieChart/styles.ts
  src/components/activities/ActivityCell/index.tsx
  src/components/camera/Camera/index.tsx
  src/components/cards/Audio/index.tsx
  src/types/IoniconsType.ts
  yarn.lock
Labels: dependencies

#612 COM-3675 : display tooltip
  src/screens/courses/cardTemplates/SurveyCard/index.tsx
  src/screens/courses/cardTemplates/SurveyCard/styles.ts
  src/types/CardType.tsx
Labels: dev

#613 COM-3678 : add questionnaire type
  src/core/data/constants.ts
  src/types/QuestionnaireType.ts
Labels: dev
