Repository CompaniTech/compani-formation, pull requests merged in 2024-02, with the labels that each got.

#601 COM-3649 - remove warning on courseprofile scrollview
  src/screens/courses/profile/LearnerCourseProfile/index.tsx
  src/screens/courses/profile/TrainerCourseProfile/index.tsx
  src/screens/courses/profile/helper.tsx
Labels: bug

#600 COM-3643: fix pro guard rules
  app.config.js
Labels: bug

#596 update-version-2-23-0: update version to 2.23.0
  app.config.js
  eas.json
Labels: dev

#602 remove useless spaces + add comma
  app.config.js
Labels: bug

#603 Com 3657
  app.config.js
  package.json
  src/AppContainer/index.tsx
  src/api/attendanceSheets.ts
  src/api/authentication.ts
  src/api/courses.ts
  src/api/users.ts
  src/core/data/constants.ts
  src/core/helpers/dates/companiDates.ts
  src/core/helpers/dates/companiDurations.ts
  src/core/helpers/notifications.ts
  src/navigation/AppNavigation/index.tsx
  src/screens/courses/CardScreen/index.tsx
  src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx
  src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
  src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx
  src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx
  src/screens/courses/profile/AdminCourseProfile/index.tsx
  src/screens/courses/profile/LearnerCourseProfile/index.tsx
  src/screens/courses/profile/SubProgramProfile/index.tsx
  src/screens/courses/profile/SubProgramProfile/styles.ts
  src/screens/courses/profile/TrainerCourseProfile/index.tsx
  src/screens/courses/profile/helper.tsx
  src/screens/explore/BlendedAbout/index.tsx
  src/styles/fonts.ts
  yarn.lock
Labels: dependencies

#604 update pull request template
  .github/pull_request_template.md
Labels: bug
